# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: nil's blog
email: guorenjun@outlook.com
description: nil's personal technical blog. about .net/nodejs and so on...
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://guorj.com" # the base hostname & protocol for your site
twitter_username: grj1046
github_username:  grj1046

# Build settings
markdown: kramdown
